### ISSUE TITLE
Can't use get methods after converting unixtime value to Jiffy object.

### ISSUE THREAD

**Issue by soham1sawant** [jama5262/jiffy#112]
**Describe the bug**
After converting unixtime to Jiffy object by Jiffy.unix() i can't use the .day to get the day from the converted time.

`void convertTime(int unixTime) {
    var dateDay = Jiffy.unix(unixTime);
    print(dateDay);
  }
`

**Expected behaviour**
I expect to be able to use the get properties on the converted JIffy object from the unix time value(e.g : 1617345000) .

**Comment by jama5262** [comment]
```dart
var timestamp = 1617345000;

var jiffy = Jiffy.unix(timestamp);

var format = jiffy.yMMMEdjm; // Fri, Apr 2, 2021 9:30 AM
var day = jiffy.day; // 6
var date = jiffy.date; // 2
```

@soham1sawant I am not fully understanding what you mean by `i can't use the .day to get the day from the converted time`, could you please explain more
