### ISSUE TITLE
Locale sv - Week should start on a Monday

### ISSUE THREAD

**Issue by SuperKrallan** [jama5262/jiffy#115]
**Describe the bug**
When having 'sv' as locale (which is great, thanks!), then you get a Sunday as start of the week, that's not correct. In Sweden we use Monday as start of the week since we follow the ISO-8601 standard as most of Europe does. This bug is in the 4.1.0 version, but I guess it has been there since the adding of the Swedish Locale 3.0.1.

in the file jiffy/lib/src/locale/availableLocales.dart in line 67 it says:   _'sv': SvLocale(StartOfWeek.SUNDAY),_
...but it should be: _'sv': SvLocale(StartOfWeek.MONDAY),_

I would be very happy if you can fix it.

/ SuperKrallan

**Comment by boeingjr** [comment]
Same issue but for 'nb' (Norwegian Bokmål) locale, week starts on Mondays in Norway as well.

**Comment by jama5262** [comment]
Solved by #119 and #122
