### ISSUE TITLE
[QUESTION] Do Getters and Setters exist for day, hour, minute etc.?

### ISSUE THREAD

**Issue by Zenahr** [jama5262/jiffy#117]
Do Getters and Setters exist for day, hour, minute etc.?

Example scenario in which this would be useful:

Say I get a TimeOfDay object inside Flutter because a user used a `TimePicker`.
Assume that I'd like to convert that to a `Jiffy` variable. To do that I'd have to somehow pass the hour and minute values I've got from `TimeOfDay` to the `Jiffy()` constructor or I'd have to overwrite the `hour` and `minute` properties of my Jiffy object.

So my question is basically whether I can directly set properties or not.

i.e.

```dart
TimeOfDay tod         = TimeOfDay.now();
Jiffy     jiff        = Jiffy();
          jiff.hour   = tod.hour;
          jiff.minute = tod.minute;
```

**Comment by jama5262** [comment]
@Zenahr Thanks for the issue, `Jiffy` does not support `TimeOfDay` as a parameter, but there are two approaches to convert it to `JIffy`

Since `TimeOfDay` only has only the hour and minute, then you can use maps that is supported by `Jiffy`, see the example below

```dart
TimeOfDay tod  = TimeOfDay.now();

Jiffy jiffy = Jiffy({
  "hour": tod.hour,
  "minutes": tod.minute
});
```

Hope i answered your issue

**Comment by Zenahr** [comment]
@jama5262 that's neat! I'm assuming that the other values such as `day`, `month` etc. will be initialized automatically then.

**Comment by jama5262** [comment]
@Zenahr Yes that is correct
