### ISSUE TITLE
Ideas on Jiffy

### ISSUE THREAD

**Issue by calvintam236** [jama5262/jiffy#118]
1. There should be `operator==()` aliasing `.isSame()`.
2. Same concept applies for `.isSameOrBefore()`, `.isSameOrAfter()`, `.isBefore()`, `.isAfter()`.
3. This will provide a native Dart way for sorting like in a `List`.
4. `.isJiffy()` and `.isDateTime()` can be done by `XXX is Jiffy` or `is DateTime`. These two functions can be eliminated.
5. The locale should be default to device locale and failover to `en` if not supported instead of requiring to set locale to use on every single time.

**Comment by calvintam236** [comment]
@AadumKhor thanks for making changes in #121.

I might not be clear on explaining 2):

Can we add add more operator overloads on `Jiffy` so we can just do `<`, `>`, `<=`, `>=` between `Jiffy`s?

This makes more sense for condition checking and builds foundation for 3).

**Comment by AadumKhor** [comment]
Excellent suggestion, will make the changes to the PR. Thanks!

**Comment by jama5262** [comment]
Please lets have different PRs for each idea in this issue, so that it will be easy to track and review the changes
