### ISSUE TITLE
Leap year miscalculation when adding months and days

### ISSUE THREAD

**Issue by itai42** [jama5262/jiffy#126]
addition across leap year boundary is miscalculated.

Test to reproduce:

    test(
        'test Jiffy().add() with leap-year boundary addition should add and return correct date time',
            () {
          expect(
              (Jiffy('2023-1-28 12:00:00', 'yyyy-MM-dd hh:mm:ss')
                ..add(years: 1, months: 1, days: 1))
                  .dateTime
                  .toString(),
              '2024-02-29 00:00:00.000');
        });

will give '2024-03-01 00:00:00.000' - which is same as adding 1 year and 1 month.
sorry for not creating a branch and pull request for fix - time presses - I will if you need me to.

**Comment by jama5262** [comment]
Hello! I would like to request that you try reproducing the issue using the latest version of Jiffy, version 6.0.0 or higher. If the issue persists, please don't hesitate to reopen this issue. For now, I'll go ahead and close it. Thank you!
