### ISSUE TITLE
Support for a fromNow taking only dates into account

### ISSUE THREAD

**Issue by TheCarpetMerchant** [jama5262/jiffy#129]
Either by passing an argument to fromNow() or making a fromToday() function.

This is needed for me as the user goes through his stuff day-by-day.

**Comment by calvintam236** [comment]
Do you mean this?

```dart
var dateTime = DateTime.now();
Jiffy(dateTime);
// or
Jiffy(DateTime.now());
```

https://github.com/jama5262/jiffy/tree/v4.1.0/doc#datetime

**Comment by TheCarpetMerchant** [comment]
I've abandoned the use of Jiffy due to a bunch of missing features that I ended up implementing myself. I honestly don't remember which specific problem I created this ticket for, I suppose that's a lesson for next time. But I think it was problematic due to the fact that I want to show the relative date to the user, anything below day-level resolution must not be taken into account. Something like that.

I'm closing this as there is no need to keep it open for me.
