### ISSUE TITLE
Jiffy.unix throws JiffyException for dates before 2001/9/10 

### ISSUE THREAD

**Issue by zde-nekz** [jama5262/jiffy#130]
When unix timestamp in milliseconds  before 2001/9/10 is entered, it's String length is only 12. Therefore JiffyException 'The timestamp passed must be in seconds or milliseconds e.g. 1570963450 or 1570963450123' is thrown.

E.g. UTC Sun Sep 09 2001 00:00:00 will return 999993600000. 1970s dates will only have timestamp length 11. 

I think we need parameter or different method for seconds and milliseconds as parsing based on length won't work.

**Comment by jama5262** [comment]
@zde-nekz I agree with you and thanks for opening an issue on it, will work on it, also if you have any ideas to resolve this, you are welcome to contribute
