### ISSUE TITLE
A getter or method to convert Jiffy to DateTime — eg. .toDateTime()

### ISSUE THREAD

**Issue by mtskf** [jama5262/jiffy#131]
It would be great if we could easily convert from Jiffy to DateTime or vice versa.
Thanks 😊

**Comment by calvintam236** [comment]
Do you mean `Jiffy().dateTime`?

https://github.com/jama5262/jiffy/tree/v4.1.0/doc#now

**Comment by mtskf** [comment]
Thanks @calvintam236 & @jama5262 😊👍
