### ISSUE TITLE
Flutter Jiffy parses local time in UTC

### ISSUE THREAD

**Issue by anuj9196** [jama5262/jiffy#141]
**Is your feature request related to a problem? Please describe.**
Using **Flutter** and **sqflite** to save data to the local device in the following table

```
CREATE TABLE records('
          'id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, '
          'phone_number TEXT, '
          'country_code TEXT, '
          'message TEXT, '
          'created DATETIME DEFAULT CURRENT_TIMESTAMP)
```

The datetime inserted in the `created` field is without timezone information 
```
2022-01-17 19:48:34
```

Now using [**Jiffy**][1] to parse the time and display the time since the date-time, e.g., `1 minute ago`.
```
Text(Jiffy(data.created).fromNow())
```

I'm in a different timezone with offset **+05:30**, so instead of displaying `1 minute ago`, it displays `6 hours ago`.

How to parse the date-time in the local timezone instead of UTC with **Jiffy**?

**Describe the solution you'd like**
Tell Jiffy, the timezone to use for the passed date-time. Or treat as local time by default.

**Describe alternatives you've considered**

**Additional context**

**Comment by calvintam236** [comment]
Maybe this is what you are looking for? https://github.com/jama5262/jiffy/tree/master/doc#local
