### ISSUE TITLE
Jiffy.from(x)

### ISSUE THREAD

**Issue by KaruguDev** [jama5262/jiffy#142]
i am building an app using Jiffy package. and i am getting this error
![jiffy_error_screenshot](https://user-images.githubusercontent.com/9849488/151049523-d0e0e69c-dfbd-4a8f-8c72-c2347026ec24.png)
this is a snippet of my code, my variable initialization and failing code snippet
![image](https://user-images.githubusercontent.com/9849488/151050414-a39fd7c5-6e7d-40a1-bead-5269b6db8004.png)

![image](https://user-images.githubusercontent.com/9849488/151049654-86409fc7-8d78-4651-9b7f-e71ca4fc846a.png)
i am trying to get the time difference of the forecast day from today as per the documentation
![image](https://user-images.githubusercontent.com/9849488/151049963-14faa15d-bf3f-44f3-9eff-50ad5f600833.png)

i cant seem to get it working.

**Comment by jama5262** [comment]
Could you please give the latest version of Jiffy a try and let me know if the issue persists? It's difficult to debug based on the description you've provided, so I'm temporarily closing this issue. However, if the problem persists, please don't hesitate to reopen it. Thank you!
