### ISSUE TITLE
Type-safe Jiffy constructor

### ISSUE THREAD

**Issue by AlexanderFarkas** [jama5262/jiffy#143]
I would like to see Jiffy as a type-safe solution.

Use case:
You have DateTime everywhere, but you decide to write a custom Date class (because you only need dates in many places), you replace DateTime with Date. But Jiffy constructor accepts dynamic, and it doesn't throw in compile time.

I propose:
Leave `Jiffy()` empty constructor public. Make `Jiffy([var input])` private, and create factory `Jiffy.fromDateTime(DateTime date) => Jiffy._(date);` for each of types. 

`Jiffy.dateTime()`, `Jiffy.map()` are also good.

What do you think? I could PR.

**Comment by jama5262** [comment]
The new version of Jiffy, v6.0.0 now supports type-safe parsing, read more here https://github.com/jama5262/jiffy/tree/master/doc#parsing
