### ISSUE TITLE
Comparing two different instances that hold the exact same date returns false

### ISSUE THREAD

**Issue by dJani97** [jama5262/jiffy#145]
**Describe the bug**

Comparing two different instances of Jiffy that hold the exact same date results in `false`.

**To Reproduce**

Example code:

    # creating two instances with identical content
    final date1 = Jiffy().startOf(Units.MONTH);
    final date2 = Jiffy().startOf(Units.MONTH);

    # making sure they are the same
    print('Date 1 is: ${  date1.dateTime  }');
    print('Date 2 is: ${  date2.dateTime  }');

    # comparing them and printing the result
    print('These are equal: ${  date1 == date2  }');

Output:

> Date 1 is: 2022-02-01 00:00:00.000
> Date 2 is: 2022-02-01 00:00:00.000
> These are equal: false

**Expected behavior**

I would expect the result to be `true`, in the same way as `date1.dateTime == date2.dateTime` also result in `true`.

**Additional context**
    jiffy: ^5.0.0

**Comment by navaronbracke** [comment]
These objects are not the same? 

```
final date1 = Jiffy().startOf(Units.MONTH);
final date2 = Jiffy().startOf(Units.MONTH);
```

The `Jiffy()` constructor will internally call DateTime.now(). Thus you ask for `DateTime.now()` twice, which is going to be different in the microsecond range here.

```
final date = DateTime.now();

final j1 = Jiffy(date);
final j2 = Jiffy(date);

print(j1.dateTime == j2.dateTime); // true
```
