### ISSUE TITLE
Jiffy objects are not immutable

### ISSUE THREAD

**Issue by navaronbracke** [jama5262/jiffy#161]
**Is your feature request related to a problem? Please describe.**
Given the following code sample:

```
final jiffy1 = Jiffy();
final jiffy2 = jiffy1.subtract(months: 1);

print(jiffy1.dateTime);
print(jiffy2.dateTime);
```

This produces the same date for both instances.
This effectively means that a Jiffy object is not immutable.

**Describe the solution you'd like**
The `Jiffy` class should be immutable, i.e. doing manipulations that modify the internal DateTime, should return a new Jiffy instance.

**Describe alternatives you've considered**
Using `Jiffy(otherJiffy).subtract();` also works but is a bit more code.

**Additional context**
N/A

**Comment by jama5262** [comment]
This issue is fixed in the new Jiffy v6.0.0 here https://github.com/jama5262/jiffy/pull/212. Sorry for the messed up pull request

```dart
final jiffy1 = Jiffy.now();
final jiffy2 = jiffy1.subtract(months: 1);

print(jiffy1.dateTime); // 2023-03-09 14:28:40.576232
print(jiffy2.dateTime); // 2023-02-09 14:28:40.576232
```
