### ISSUE TITLE
Support durations

### ISSUE THREAD

**Issue by atn832** [jama5262/jiffy#163]
**Is your feature request related to a problem? Please describe.**
Jiffy.from is awesome because it shows human readable relative dates. I'd like to use the same feature for Durations, without the prefix or suffix (no "in ..." or "... ago").

**Describe the solution you'd like**
So, I'd like something like `Jiffy(Duration(days: 366)).someNewMethod` to return something like "a year".

**Describe alternatives you've considered**
I tried to implement my own locale to remove the prefix and suffix, but it doesn't seem like I can do this easily.

**Additional context**

**Comment by jama5262** [comment]
Hey @atn832 , thanks for the contribution, this feature looks like it will be great to have. Maybe not necessarily have a new method but we can update the existing methods to have an optional param `withoutPrefixAndSuffix` by deafult to show the prefix and suffix of the relative time

```dart
// Update the relative time functions
String fromNow({bool withoutPrefixAndSuffix = false}) { // add the new param `withoutPrefixAndSuffix`
   ...
}

String from(var input, {bool withoutPrefixAndSuffix = false}) { // add the new param `withoutPrefixAndSuffix`
   ...
}

// and you can use it like so

Jiffy().fromNow() // a year ago
Jiffy().fromNow() // 20 mins ago
Jiffy().fromNow(withoutPrefixAndSuffix: true) // a year
Jiffy().fromNow(withoutPrefixAndSuffix: true) // 20 mins

// or assume in the case of future time

Jiffy().fromNow() // in a year
Jiffy().fromNow(withoutPrefixAndSuffix: true) // a year
```

What do you think?

**Comment by atn832** [comment]
If that is much less work for you, it's a good first step.

So if you implement it your way, if someone has a Duration they want to print out, they'd have to call something like:
```dart
Jiffy(DateTime.now().add(theDuration)).fromNow(withoutPrefixAndSuffix: true)
```
Is that right?

Then we could consider adding a utility function to make it easier to use:
```dart
Jiffy.printDuration(Duration d) {
  Jiffy(DateTime.now().add(d)).fromNow(withoutPrefixAndSuffix: true);
}
```
