### ISSUE TITLE
Upgrade intl dependency to 0.18.0

### ISSUE THREAD

**Issue by kipouras** [jama5262/jiffy#167]
Is it possible to update intl dependency to the newest version 0.18.0?
Than you

**Comment by SuperKrallan** [comment]
Yes, please... :)

**Comment by eximius313** [comment]
I see that there is a PR for that: https://github.com/jama5262/jiffy/pull/173
Is there something preventing it to be merged?

**Comment by Aksoyhlc** [comment]
As a temporary solution, you can use it as follows in Pubspec.yaml file.

jiffy:
    git:
      url: https://github.com/Aksoyhlc/jiffy.git
      ref: master
