### ISSUE TITLE
How do I add new Locale?

### ISSUE THREAD

**Issue by thanhnd2812** [jama5262/jiffy#220]
I would like to add Vietnamese locale.

How can I get it? Thanks

**Comment by Kuntheasoung** [comment]
Is there any solution? I have this problem too.

**Comment by jama5262** [comment]
Hey @thanhnd2812 and @Kuntheasoung, created a discussion page, just for how to add a new locale in Jiffy https://github.com/jama5262/jiffy/discussions/231

Hope this helps
