### ISSUE TITLE
Can you the nl (Dutch) locale?

### ISSUE THREAD

**Issue by AndreJLouw** [jama5262/jiffy#221]
Please add this locale as an option

**Comment by jama5262** [comment]
Hello, the `nl` local is already available here https://github.com/jama5262/jiffy/blob/master/lib/src/locale/locales/nl_locale.dart

**Comment by Kuntheasoung** [comment]
@jama5262 Can you add km_kh (Cambodia)? I can help with translation.

**Comment by jama5262** [comment]
> @jama5262 Can you add km_kh (Cambodia)? I can help with translation.
> 
> ```
> class KHRelativeTime extends RelativeDateTime {
>   @override
>   String prefixAgo() => '';
>   @override
>   String prefixFromNow() => 'ក្នុងរយៈពេល';
>   @override
>   String suffixAgo() => 'មុន';
>   @override
>   String suffixFromNow() => '';
>   @override
>   String lessThanOneMinute(int seconds) => 'ពីរបីវិនាទី';
>   @override
>   String aboutAMinute(int minutes) => 'មួយ​នាទី';
>   @override
>   String minutes(int minutes) => '$minutes នាទី';
>   @override
>   String aboutAnHour(int minutes) => 'មួយ​ម៉ោង';
>   @override
>   String hours(int hours) => '$hours ម៉ោង';
>   @override
>   String aDay(int hours) => 'មួយថ្ងៃ';
>   @override
>   String days(int days) => '$days ថ្ងៃ';
>   @override
>   String aboutAMonth(int days) => 'មួយខែ';
>   @override
>   String months(int months) => '$months ខែ';
>   @override
>   String aboutAYear(int year) => 'មួយឆ្នាំ';
>   @override
>   String years(int years) => '$years ឆ្នាំ';
>   @override
>   String wordSeparator() => ' ';
> }
> ```

@Kuntheasoung Please create a new PR only for the km_kh (Cambodia) locale
