### ISSUE TITLE
Unable to use factory method `parse`

### ISSUE THREAD

**Issue by thapli9A** [jama5262/jiffy#222]
Unable to use factory method `parse`

```
factory Jiffy.parse(String string, {String? pattern, bool isUtc = false}) {
    return Jiffy._internal(string, pattern: pattern, isUtc: isUtc);
}
```

<img width="869" alt="Screenshot 2023-03-19 at 2 27 06 AM" src="https://user-images.githubusercontent.com/72211856/226139498-b631286e-f119-4433-a6a2-0068d9001106.png">

**Comment by thapli9A** [comment]
@jama5262 :

**Comment by jama5262** [comment]
Thanks @thapli9A taking a look now

**Comment by jama5262** [comment]
Hi @thapli9A,

I couldn't find any related issue based on your description. However, I have tested the code you provided, and it seems to be working fine. Here is what I have tried

```dart
import 'package:jiffy/jiffy.dart';

final jiffy = Jiffy.parse('2022-03-23');
print('Parsed date: ${jiffy.dateTime}'); // Parsed date: 2022-03-23 00:00:00.000
```

If you could provide additional details, such as how you imported the Jiffy library, I might be able to assist you better.

**Comment by thapli9A** [comment]
Version:  `jiffy: ^5.0.0`
import: `import 'package:jiffy/jiffy.dart';`
Code: 
```
extension DateTimeGetter on String {
  DateTime date(String format) {
    final jiffy = Jiffy.parse('2022-03-23');
    return jiffy;
  }
}
```

Error : 
<img width="999" alt="Screenshot 2023-03-19 at 2 03 08 PM" src="https://user-images.githubusercontent.com/72211856/226163132-abc7b9a7-da11-4599-af0d-b668a5fc9d44.png">

**Comment by jama5262** [comment]
Ok I see the issue now

Please update version to 

Version: `jiffy: ^6.1.0`

**Comment by thapli9A** [comment]
Okay

**Comment by jama5262** [comment]
Hopefully, this solves your issue, if it persists, please feel free to reopen this issue
