### ISSUE TITLE
Error in INTL 0.18.1

### ISSUE THREAD

**Issue by bilalsammour** [jama5262/jiffy#228]
**Describe the bug**

Jiffy depends on intl 0.18.1 that has the following error with the latest Flutter version:
```
Because [PROJECR] depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because invy depends on intl ^0.18.1, version solving failed.
``` 

**How to reproduce the bug**

* Create a Flutter version using the latest version (3.7.x).
* Add `flutter_localizations`.
* Add `jeffy`.
* You will get an error.

**Comment by jama5262** [comment]
Hey @bilalsammour , i don't think it a good idea for `Jiffy` for rollback the `Intl` version from `0.18.0` to `0.17.0`. If you really want `0.17.0` you can try `dependency_overrides` in `pubspecy.yml` file, like so

```yml
dependency_overrides:
  intl: ^0.17.0
```

I beleive this might work for you
