### ISSUE TITLE
parse string with timezone

### ISSUE THREAD

**Issue by Lomski** [jama5262/jiffy#236]
**Describe the bug**
Is there a way to parse string like this "2023-04-04T10:48:15+11:00" with version 6 jiffy?
In version 4.1.0 you just use Jiffy("2023-04-04T10:48:15+11:00") and get time in your device timezone. For example in +10:00 timezone you get string "2023-04-04T09:48:15.000" by using Jiffy("2023-04-04T10:48:15+11:00").format().

**Comment by jama5262** [comment]
Hello @Lomski 

So this seems like Jiffy cannot parse this string alone without a pattern, so to solve your issue, try the following

Your date time string `2023-04-04T10:48:15+11:00` has a timezone at the end, so we create a pattern that will help Jiffy to parse it. The pattern will be `yyyy-MM-ddTHH:mm:ssZ`. And how to use it, see below

```dart
Jiffy.parse('2023-04-04T10:48:15+11:00', pattern: 'yyyy-MM-ddTHH:mm:ssZ').format(); // 2023-04-04T10:48:15.000
```

The above code will give you what you expected, hopefully, this helps.

Jiffy, runs on top of DateFormat, so you can also learn more about the patterns here [DateFormat patterns](https://pub.dev/documentation/intl/latest/intl/DateFormat-class.html#:~:text=DateFormat%20is%20for%20formatting%20and,name%2C%20field%20order%2C%20etc.)
