### ISSUE TITLE
The wrong locale data while there are parsing data through endOf function

### ISSUE THREAD

**Issue by klnfreedom** [jama5262/jiffy#241]
`jiffy: ^6.1.0`

**Describe the bug**

I am having trouble identifying the correct first day of the week.
It seems that the library does not support my current locale, so it defaults to `EnUsLocale()`. However, I've noticed that the first day of the week in this locale is Sunday, which may not be the case for all users. For example, in my time zone, the first day of the week is actually Monday.

**How to reproduce the bug**

- Unsupported locale; /// system locale is uk_UA
- Anyway, the lib supports Ukraine Locale, but this comparing `'uk'.contains('uk_UA')` always gets the false result. So, the lib will take `EnUsLocale()`;
- This situation is not limited to my location but also extends to other areas that aren't supported by the library.

```
final today = Jiffy.now();
final end = today.endOf(Unit.week).dateTime;
```

**What is the expected behavior**

Correctly determining the weekdays for the current locale.

**Screenshots**
lib -> src -> jiffy.dart -> 218 row
![image](https://github.com/jama5262/jiffy/assets/72871325/c0f3a9e6-6137-43df-819e-c595ca987164)

lib -> src -> manipulator.dart -> 139 row
![image](https://github.com/jama5262/jiffy/assets/72871325/5eee4138-4f70-4e2f-9497-36c9a3863eb0)

**Comment by jama5262** [comment]
Similar to #64

**Comment by jama5262** [comment]
Please follow the issue linked above, since its related, working on making the start of week configurable and also lets users to create their own custom locales, so that they are not limited only Jiffy locales
