### ISSUE TITLE
How to remove dot?

### ISSUE THREAD

**Issue by adrianvintu** [jama5262/jiffy#242]
I have my locale set to german: `await Jiffy.locale('de');`

I print `date.format('EEE do MMMM yyyy')`, for example: `Sa. 10. Juni 2023`.

I want to remove the dot from `Sa.`, but not from Juni. Can I do this somehow?

Needed aoutput: `Sa 10. Juni 2023`

**Comment by kubawich** [comment]
I see now way to do this with Jiffy, modify string by dart code.

**Comment by jama5262** [comment]
@adrianvintu 

This is not an issue with Jiffy, this is an issue with the Intl library that Jiffy runs on top off to format dates.

A hacky way will be using some kind of string manipulation, where you can remove the first found dot. 

Something like this 

```dart
String input = "Sa. 10. Juni 2023";
  
// Use a regular expression to find the first dot and replace it with nothing
String result = input.replaceFirst(RegExp(r'\.'), '');

print(result); // Output: "Sa 10. Juni 2023"
```

**Comment by adrianvintu** [comment]
Thank you @jama5262 !
