### ISSUE TITLE
Error: JiffyException: The locale `ro`

### ISSUE THREAD

**Issue by RoyalCoder88** [jama5262/jiffy#250]
Hi thanks for your great package,

I have errors with localizations, I have supported locals as:
`supportedLocales: const [Locale('en', 'GB'), Locale('ro', 'RO')],`

and when I'm trying to use `await Jiffy.setLocale('ro');` I get an exception:

`Error: JiffyException: The locale "ro" is not supported, please check here for a list of supported locales
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49  throw_`

How can I fix this issue, thanks in advance!

My flutter doctor -v:

>  [√] Flutter (Channel stable, 3.13.4, on Microsoft Windows [Version 10.0.22621.2283], locale en-GB)
>     • Flutter version 3.13.4 on channel stable at C:\tools\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 367f9ea16b (2 days ago), 2023-09-12 23:27:53 -0500
>     • Engine revision 9064459a8b
>     • Dart version 3.1.2
>     • DevTools version 2.25.0
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
>     • Android SDK at C:\Users\burac\AppData\Local\Android\sdk
>     • Platform android-33, build-tools 33.0.1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.4.4)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.4.33213.308
>     • Windows 10 SDK version 10.0.22000.0
> 
> [√] Android Studio (version 2021.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
> 
> [√] VS Code (version 1.82.1)
>     • VS Code at C:\Users\burac\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.72.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22621.2283]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.188
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.76
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> • No issues found!

**Comment by jama5262** [comment]
Hey @RoyalCoder88 

From the error, it seems like the `ro` locale, that is the Romanian locale is not supported for Jiffy

Jiffy if happy to welcome new locales, but I myself, I'm not familiar with the `ro_*`  locales

To support it, you can contribute to add your locale, you can follow the discussion instructions here https://github.com/jama5262/jiffy/discussions/231
