### ISSUE TITLE
Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.18.1

### ISSUE THREAD

**Issue by laterdayi** [jama5262/jiffy#265]
Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.18.1

**Comment by jama5262** [comment]
Sorry but i dont understand your issue, could you please elaborate

**Comment by laterdayi** [comment]
When using jiffy, he suggested that jiffy intl would conflict with flutter_localizations intl

**Comment by jama5262** [comment]
If i understand you right, you are using `flutter_localizations` that depends on `0.18.1`,

You can try to use `dependency_overrides` in your pubspec.yaml file, like so

```yaml
dependency_overrides:
  intl: ^0.18.1
```

Can you try the above and tell me if it works

**Comment by laterdayi** [comment]
@jama5262   intl: ^0.18.1

Resolving dependencies... 
Because zhuoshengwei_mobile depends on jiffy ^6.3.0 which depends on intl ^0.19.0, intl ^0.19.0 is required.
So, because zhuoshengwei_mobile depends on intl ^0.18.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on jiffy: flutter pub add jiffy:^6.2.1   
PS E:\projects\zhuoshengwei-mobile>

**Comment by laterdayi** [comment]
The problem still exists
