### ISSUE TITLE
Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.18.1

### ISSUE THREAD

**Issue by laterdayi** [jama5262/jiffy#271]
Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.18.1

```
dependency_overrides:
  intl: ^0.18.1
```

The problem still exists

ref https://github.com/jama5262/jiffy/issues/265

**Comment by trongnghiagenki** [comment]
This is flutter_localizations from Flutter SDK issue.

Afaik they have already solved it in Flutter 3.21 beta. At this moment you can use Jiffy 6.2.1 or wait for 3.21 to be released.

**Comment by g-apparence** [comment]
Would love a simple update with the upgrade of the dep 🙏🏻

**Comment by jama5262** [comment]
Working on it now 👍

**Comment by jama5262** [comment]
@laterdayi @g-apparence New version released https://pub.dev/packages/jiffy/versions/6.3.2

Please try it out and test if it works now

**Comment by g-apparence** [comment]
THank you 🙏🏻
