### ISSUE TITLE
Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.20.1, jiffy >=6.2.2 is incompatible with   flutter_localizations from sdk.

### ISSUE THREAD

**Issue by saucelooker** [jama5262/jiffy#285]
Hello. I have this problem now. Any ideas other than downgrading flutter?

Because jiffy >=6.2.2 depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.20.1, jiffy >=6.2.2 is incompatible with flutter_localizations from sdk.

**Comment by jama5262** [comment]
Related to https://github.com/jama5262/jiffy/issues/271

Let me release a new version now

**Comment by saucelooker** [comment]
Everything works. Thank you very much!!!
