### ISSUE TITLE
startOf("w") and endOf("") don't support locales + week getter bug

### ISSUE THREAD

**Issue by MrCasCode** [jama5262/jiffy#31]
**Describe the bug**
The current implementation of startOf() doesn't support locales customization. That makes that startOf("w") to always return sunday at midnight as the first day of the week without possibility to return monday depending of the locale.

```
await Jiffy.locale("fr");

var today = Jiffy();
today.yMMMEdj; // "11 nov. 2019 08:29" --> Monday

var startOfWeek = Jiffy(Jiffy().startOf("w"));
startOfWeek.yMMMEdj; // "10 nov. 2019 00:00" --> Sunday

var endOfWeek = Jiffy(Jiffy().endOf("w"));
endOfWeek.yMMMEdj; // "16 nov. 2019 23:59" --> Saturday
```

Also I think there is something wrong with the .week getter
```
today.week // 46
startOfWeek.week // 45
endOfWeek.week // 45

```
**Expected behavior**

- startOf("w") should return monday for an European timezone
- today's week, startOfWeek and endOfWeek should be in the same week  

**Additional context**
I put the two issues into the same because I think they have the same root cause -> locales support.

As discussed earlier, startOf() and endOf() don't support locales customization and they are coded for the US/Canada...

And the week getter makes use of DateTime.weekday that is coded according to the international standard ISO 8601, where Monday is the first day of the week so it returns the week before when asked for startOf("w")

**Comment by jama5262** [comment]
@MrCasCode I was able to fix startOf and endOf week base on the locale. You can check it out here.
https://github.com/jama5262/jiffy/commit/60f1cc7a390d69a42fbe0a0dda7d39d4f9efecf6 that is the `fix-week` branch

e.g US locale, start week day is Sunday to Saturday
e.g Like French, start week day is Monday to Sunday
e.g Like Arabic, start week day is Saturday to Friday

```
await Jiffy.locale("fr");

var today = Jiffy();
today.yMMMEdjm; // "11 nov. 2019 08:29" --> Monday

var startOfWeek = Jiffy(today)..startOf("w");
startOfWeek.yMMMEdjm; // "11 nov. 2019 00:00" --> Monday

var endOfWeek = Jiffy(today)..endOf("w");
endOfWeek.yMMMEdjm; // "17 nov. 2019 23:59" --> Sunday
```

And for the week getter, I do agree that the `today, start of week and end of week` should have the same week of year. But  I had a hard time finding the best accurate solution.

If you have any way of solving this, please feel free to contribute to the `fix-week` branch

**Comment by MrCasCode** [comment]
Hi @jama5262 thank you for your contribution! I'm sorry for the late answer I've been quite busy this week.
I've been thinking in how to do this properly, I will try some fix this weekend.

**Comment by MrCasCode** [comment]
I've modified the day getter so that it returns the day of the week in function of the locales. 

I'm not an expert in standardization but I think it would be the correct behavior to return the weekday in function of the current locale so that when asking for the weekday:
locale: ```"en"```  
day: sunday
current return: 7
expected return: 1

Test code
```
  await Jiffy.locale("fr");

  var today = Jiffy();
  print("Today:       " + today.yMMMEdjm + " day: ${Jiffy(today).day} week: ${today.week}");

  var startOfWeek = Jiffy(today)..startOf("w");
  print("startOfWeek: " + startOfWeek.yMMMEdjm + " day: ${Jiffy(startOfWeek).day} week: ${startOfWeek.week}");

  var endOfWeek = Jiffy(today)..endOf("w");
  print("endOfWeek:   " + endOfWeek.yMMMEdjm + " day: ${Jiffy(endOfWeek).day} week: ${endOfWeek.week}");
```
Output

```
Today:       dim. 24 nov. 2019 09:52 day: 7 week: 47
startOfWeek: lun. 18 nov. 2019 00:00 day: 1 week: 47
endOfWeek:   dim. 24 nov. 2019 23:59 day: 7 week: 47
```

Using ```"en"``` locale

```
Today:       Sun, Nov 24, 2019 9:56 AM day: 1 week: 48
startOfWeek: Sun, Nov 24, 2019 12:00 AM day: 1 week: 48
endOfWeek:   Sat, Nov 30, 2019 11:59 PM day: 7 week: 48

```

I'm pushing the commit
