### ISSUE TITLE
Undefined name 'Units'.

### ISSUE THREAD

**Issue by kterrago18** [jama5262/jiffy#54]
Unable to use 'Units'

`String  d = Jiffy(date).isAfter(toUtc, Units.YEAR ) ? 'Date' : Jiffy(date).from(toUtc);`

**Comment by jama5262** [comment]
Hi @kterrago18, I tested this on my end and it works. So, I think the issue maybe you are not using the **new version released a couple of days ago** and it is [v3.0.0](https://github.com/jama5262/jiffy/releases) where `Units` was introduced. So maybe update to a newer version [v3.0.0](https://github.com/jama5262/jiffy/releases) and let me now if it works

**Comment by parth22** [comment]
@jama5262 I'm using ```v3.0.0``` with ```final test = Jiffy(selectedStartDate).diff(Jiffy(selectedEndDate), Units.MONTH);``` and got the same error.

**Comment by jama5262** [comment]
@parth22 @kterrago18 I was able to find the bug. The problem was that the enums were not exported to be publicly used outside of the package. I will resolve and release a new version quickly

**Comment by jama5262** [comment]
@kterrago18 and @parth22 The issue is now resolved, please update to version `3.0.1` for new changes and confirm it is working
