### ISSUE TITLE
Query methods mutate the underlying date instance

### ISSUE THREAD

**Issue by brokenalarms** [jama5262/jiffy#59]
**Describe the bug**
Any queries appear to mutate the original underlying date instance. This is a pretty major bug as performing any query therefore changes the datetime unexpectedly. Have tested it with `isSame`, but it looks like any query calling `startOf` `endOf` with less than ms granularity will cause the original date to lose that granularity.

**To Reproduce**
```
var date = Jiffy(); // date is 04/07/20 23:30
var is sameDay = date.isSame(Jiffy(), Units.DAY);
// date is now 04/07/20 23:59:59, due to calling startOf which directly changes the underlying
`_datetime` object by resetting it to `DAY` granularity to use it for comparison, instead of creating a new comparator for this purpose.
```

**Expected behavior**
Querying my dates don't change them :)

**Comment by brokenalarms** [comment]
really, every `Jiffy(1).add(1).subtract(3)` (just example with number for simplicity) should be immutable and returning a fresh object each time, so that intermediate steps can be saved, eg
```
var one = Jiffy(1);
var three = one.add(2);
var two = three.subtract(1);
```
 This is what I expected from the docs  esp. with mentions of 'returning a Jiffy instance'. It looks like all the `clone` methods from momentjs that ensure manipulations are safe are not present in this package.

**Comment by imtoori** [comment]
I agree, that's the expected and best way

**Comment by Tinhorn** [comment]
Thanks for working on this right away
When is this gonna come out?
This bug is going to cause a lot of subtle bugs in projects using this package

**Comment by arok** [comment]
Same for me when the bug will be fixed?

**Comment by jama5262** [comment]
Jiffy version 4.0.0 will account for `isSame`, `isBefore` and `isAfter` methods changing the datetime  

And Jiffy will also support cloning, see below

```
var a = Jiffy([2021]);
var b = Jiffy(a);
a.add(year: 10);
a.year; // 2031
b.year; // 2021
```
or you can use the `clone` method
```
var a = Jiffy([2021]);
var b = a.clone();
a.add(year: 10);
a.year; // 2031
b.year; // 2021
```
