### ISSUE TITLE
Jiffy().day is not returning the correct ID

### ISSUE THREAD

**Issue by schankam** [jama5262/jiffy#60]
**Describe the bug**
On my current timezone, we are Thursday. When calling Jiffy().day, the returning value is 5 (should be 4).

If I am printing this:

print(DateTime.now().weekday);

I am correctly getting 4.

**To Reproduce**
Just print (Jiffy().day);

**Expected behavior**
According to the documentation:

Get day of week (Returns from 0 - 6 [Sunday - Saturday])

Jiffy().day should return the correct ID of the week day

**Screenshots**
<img width="496" alt="Screenshot 2020-04-09 at 21 56 55" src="https://user-images.githubusercontent.com/3543017/78925826-1b0d2a80-7aad-11ea-81e3-c0f973190dbe.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version 3.0.1

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Max emulator
 - OS: ios 13+

**Comment by talamaska** [comment]
@schankam the guy did made that on purpose he is reflecting JS DateTime API, which is odd. I already reported the same issue basically. He is insisting that it is pretty standard and i want a logic parity with Dart DateTime, so in the ends I deleted the library from my project and used helper functions to get the stuff I don't have from Dart DateTime.

**Comment by schankam** [comment]
@talamaska If that's the case, the documentation should at least reflect what's the real output.

**Comment by talamaska** [comment]
@schankam it is reflected in the docs
Day of week
Get day of week (Returns from 0 - 6 [Sunday - Saturday])
Jiffy().day;

In dart DateTime.now().weekday returns from 1 to 7 - there is your difference

**Comment by jama5262** [comment]
@talamaska and @schankam . I will be moving this issue to #58 . We will discuss there
