### ISSUE TITLE
Cannot parse date with format yyyyMMddhhmmss

### ISSUE THREAD

**Issue by adolfdsilva** [jama5262/jiffy#65]
**Describe the bug**
Cannot parse date with format yyyyMMddhhmmss, stacktrace:

```
ERROR: FormatException: Trying to read MM from 20200610094430 at position 14
package:intl/src/intl/date_format_field.dart 87:5   _DateFormatField.throwFormatException
package:intl/src/intl/date_format_field.dart 337:7  _DateFormatPatternField.parseField
package:intl/src/intl/date_format_field.dart 250:5  _DateFormatPatternField.parse
package:intl/src/intl/date_format.dart 374:13       DateFormat._parse
package:intl/src/intl/date_format.dart 303:7        DateFormat.parse
package:jiffy/src/jiffy.dart 74:14                  Jiffy._parse
package:jiffy/src/jiffy.dart 17:17                  new Jiffy
test/widget_test.dart 192:22                        main.<fn>


``` 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jama5262** [comment]
Hi @adolfdsilva. Yes you will get this error because Jiffy runs on top of DateFormat, and DateFormat tends to give this error, but in Jiffy, we are working on fixing this as there is another similar issue.

I will be closing this issue, we will discuss here #45

**Comment by jama5262** [comment]
@adolfdsilva Jiffy does not support this currently but there is a workaround. See below

```dart
var regex = RegExp(r'(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})');
  
var dateTime = regex.firstMatch('20200610094430')
      !.groups([1, 2, 3, 4, 5, 6])
      .map((e) => int.parse(e!))
      .toList(); // <- this will return a list of date [2020, 6, 10, 9, 44, 30]

// Then pass in the dateTime
print(Jiffy(dateTime ).dateTime; // 2020-06-10 09:44:30.000
```

**Comment by norman93sun** [comment]
> @adolfdsilva Jiffy does not support this currently but there is a workaround. See below
> 
> ```dart
> var regex = RegExp(r'(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})');
>   
> var dateTime = regex.firstMatch('20200610094430')
>       !.groups([1, 2, 3, 4, 5, 6])
>       .map((e) => int.parse(e!))
>       .toList(); // <- this will return a list of date [2020, 6, 10, 9, 44, 30]
> 
> // Then pass in the dateTime
> Jiffy(dateTime).dateTime; // 2020-06-10 09:44:30.000
> ```

Any update for this format?
