### ISSUE TITLE
Jiffy Difference

### ISSUE THREAD

**Issue by jkd359** [jama5262/jiffy#68]
I am unable to receive back a double from adding 'true' as a third parameter when using Units.HOUR: 
```
var jiffy1 = Jiffy("10:00 AM", "h:mm a");
var jiffy2 = Jiffy("10:30 PM", "h:mm a");

jiffy1.diff(jiffy2, Units.HOUR); // -12
jiffy1.diff(jiffy2, Units.HOUR, true); // -12, from my understanding should be -12.5
```
My results always truncate to a whole number.

Anyone else get this when trying?

**Comment by jaimesma18** [comment]
me too, any solution?

**Comment by jama5262** [comment]
@jkd359 Thanks for finding the bug, it has been fixed now, should be available in the `master` branch soon
