### ISSUE TITLE
Locale de_DE not supported by fromNow()

### ISSUE THREAD

**Issue by SebRut** [jama5262/jiffy#70]
**Describe the bug**
The result of `Jiffy().fromNow(...)` is returning the default english texts if the locale is set to 'de_DE'.

**To Reproduce**
```dart
final locale = await findSystemLocale(); //returns 'de_DE'
await Jiffy.locale(locale);

final result = Jiffy().fromNow()
```

**Expected behavior**
`result` should display the relative time in german.

**Additional context**
I guess this occurs as relative time only checks for 'de`, 'deat' and 'dech', not 'dede'.

**Comment by jama5262** [comment]
@SebRut Indeed the `de_DE` is not supported, but as you mentioned in the issue
`'de', 'deat' and 'dech'` are only checked for relative time like `fromNow()` and `from()`

But if you would like `de_DE` to be supported, you can create a PR and add the locale to `Jiffy`
