### ISSUE TITLE
Jiffy methods should always return a Jiffy type

### ISSUE THREAD

**Issue by magpiedigital** [jama5262/jiffy#73]
**Is your feature request related to a problem? Please describe.**
It's difficult to reason when a jiffy returns a different type, and it makes chaining calculations verbose and confusing.

    final beginning = Jiffy(date).startOf(Units.DAY);
    final end = Jiffy(date)
      ..startOf(Units.DAY)
      ..add(days: 1);

    print(beginning); // returns DateTime
    print(end); // returns Jiffy

**Describe the solution you'd like**
Jiffy methods should always return a Jiffy type. That way the above calculation would become

    final beginning = Jiffy(date).startOf(Units.DAY);
    final end = beginning.add(days: 1);

    print(beginning.dateTime);
    print(end.dateTime);

**Describe alternatives you've considered**
Rather than using moment.js in my js projects, I've been using [Luxon](https://github.com/moment/luxon) (also maintained by moment) which I've found is infinitely better. Personally if i was to make a date package in dart I would base it off Luxon instead.

**Comment by simonckenyon** [comment]
This took me a while to understand.
It is a good library, but why some methods return a DateTime and others return a Jiffy is a little baffling.
Please make all the return types Jiffy, except for local() and utc() of course.
And please make all methods builders while you are at it.

**Comment by jama5262** [comment]
@magpiedigital and @simonckenyon I agree, this will be changed in the next version 4.0.0 coming soon
