### ISSUE TITLE
Jiffy().week gives the wrong week

### ISSUE THREAD

**Issue by Adrian4777** [jama5262/jiffy#79]
Jiffy().week is giving me the wrong week. Im trying to get the week number of 2020/09/06 and it gives me week 37. But it should be 36. (Monday-Sunday kind of week)

**Comment by aguthstuditemps** [comment]
Same Problem here. Jiffy does not seem to count weeks the same way as the ISO calendar does.
Week 1 of 2020 starts at 2019-12-30 in ISO, but `Jiffy(DateTime(2019, 12, 30))` returns 53 instead of 1

**Comment by Adrian4777** [comment]
Well. Im a bit new to this, but heres how I solved it, it´s a bit rough. But it gets the work done.

var _pastDate = DateFormat('EEEE');

int _getWeekNumber() {

  int _addDay = 1;

  String _firstDayOfYear =
      _pastDate.format(DateTime(int.parse(_selectedYear), 1, 1));

  int _dayOfYear =
      Jiffy(yourYear, yourMonth, yourDay])
          .dayOfYear;

  if (_firstDayOfYear == "Monday") {
    _addDay = 0;
  } else if (_firstDayOfYear == "Tuesday") {
    _addDay = 1;
  } else if (_firstDayOfYear == "Wednesday") {
    _addDay = 2;
  } else if (_firstDayOfYear == "Thursday") {
    _addDay = 3;
  } else if (_firstDayOfYear == "Friday") {
    _addDay = 4;
  } else if (_firstDayOfYear == "Saturday") {
    _addDay = 5;
  } else if (_firstDayOfYear == "Sunday") {
    _addDay = 6;
  }

double weekCalc (){
  var _weekNumber = (_addDay+_dayOfYear)/7;
  return _weekNumber;
}

  return weekCalc().ceil();
}

**Comment by pal** [comment]
That's a weird piece of code @Adrian4777, anything tested & sharable?

**Comment by Adrian4777** [comment]
If only i found that solution earlier. But thanks!

Don´t think you need it, but here is an improved version of the weird code, might be a bit easier to understand. I have tested it, and it seems to be working (so far). 

I had no idea some years has 53 weeks in them, was having time before figuring that out. 

```
int _getWeek(int yourYear, int yourMonth, int yourDay) {
  DateFormat stringFormat = DateFormat('EEEE');

  int weekCalculator1(int yourYear, int yourMonth, int yourDay) {
    int addADay;

    String _firstDayOfYear = stringFormat.format(DateTime(yourYear, 1, 1));

    if (_firstDayOfYear == "Monday") {
      addADay = 0;
    } else if (_firstDayOfYear == "Tuesday") {
      addADay = 1;
    } else if (_firstDayOfYear == "Wednesday") {
      addADay = 2;
    } else if (_firstDayOfYear == "Thursday") {
      addADay = 3;
    } else if (_firstDayOfYear == "Friday") {
      addADay = 4;
    } else if (_firstDayOfYear == "Saturday") {
      addADay = 5;
    } else if (_firstDayOfYear == "Sunday") {
      addADay = 6;
    }

    return ((addADay + Jiffy([yourYear, yourMonth, yourDay]).dayOfYear) / 7)
        .ceil();
  }

  bool fiftythreeWeeksCalc() {
    String day = stringFormat.format(DateTime(yourYear - 1, 1, 1));
    bool leapYear = Jiffy([yourYear - 1, 1, 1]).isLeapYear;
    if (day == 'Thursday') {
      return true;
    } else if (day == 'Wednesday' && leapYear == true) {
      return true;
    } else {
      return false;
    }
  }

  int weekCalculator2() {
    if (fiftythreeWeeksCalc() == true && yourMonth == 1 && yourDay == 1) {
      return 53;
    } else if (fiftythreeWeeksCalc() == true &&
        yourMonth == 1 &&
        yourDay == 2) {
      return 53;
    } else if (fiftythreeWeeksCalc() == true &&
        yourMonth == 1 &&
        yourDay == 3) {
      return 53;
    } else if (fiftythreeWeeksCalc() == true) {
      return weekCalculator1(yourYear, yourMonth, yourDay) - 1;
    } else {
      return weekCalculator1(yourYear, yourMonth, yourDay);
    }
  }

  return weekCalculator2();
}
```
