### ISSUE TITLE
Jiffy().week gives me a wrong week number on Sunday

### ISSUE THREAD

**Issue by macmatrix** [jama5262/jiffy#80]
Hello

I have seen a strange behavior with the Jiffy package in my flutter app. Here is my code 

```
final refDate = new DateTime(2020, 10, 18); // 18 Oct 2020
int weekNumber(DateTime date) {
  int dayOfYear = int.parse(DateFormat("D").format(date));
  return ((dayOfYear - date.weekday + 10) / 7).floor();
}

print(weekNumber(refDate));
print(Jiffy(refDate).week.toString());
```

The output is as follow

> 42
> 43

Can anyone explain when? I see the .week function call the same formula... ([link](https://pub.dev/documentation/jiffy/latest/jiffy/Jiffy/week.html))

Thanks!

**Comment by jama5262** [comment]
Hi, @macmatrix same issue as #58. Basically, we should add a setting for this, on which you can choose which start day you want. Hence the different week numbers your as seeing
