### ISSUE TITLE
Update intl to ^0.17.0

### ISSUE THREAD

**Issue by apgapg** [jama5262/jiffy#90]
**Describe the bug**
Jiffy depends on intl but into latest is now 0.17.0.

**Comment by jama5262** [comment]
@apgapg version 0.17.0. seems to be in the preview stage, should we still add it or wait for it to be a stable version

**Comment by apgapg** [comment]
Flutter will enter 2.0 with null safety enabled on 3 rd march ie 2 days after. I guess preview version will become stable.
