### ISSUE TITLE
Support flutter 2

### ISSUE THREAD

**Issue by saharvx9** [jama5262/jiffy#96]
Not working in flutter 2

**Comment by jama5262** [comment]
@saharvx9 version `4.0.0` to be released by end of today, which supports flutter 2

**Comment by leszekkrol** [comment]
Great!

**Comment by jama5262** [comment]
Jiffy 4.0.0 avalilable now

**Comment by jlnrrg** [comment]
@jama5262 thank you for the fast realization. :+1:
